version: '3.8'

services:

  ehr_aa:
    env_file:
      - .env
    image: ${IMAGE_NAME}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    #   args:
    #   - CONTAINER_DEVSPACE=${CONTAINER_DEVSPACE}
    container_name: ${CONTAINER_NAME}
    entrypoint:
       [
        "/bin/bash",
        "/usr/local/entrypoints/jbs/main.sh"
      ]
    volumes:
      - ${LOCAL_PROJECT_ROOT}:${CONTAINER_PROJECT_ROOT}
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:${CONTAINER_SSH_PORT}:22"
    init: true
    stdin_open: true
    tty: true

  postgres_mimiciii:
    image: duanegoodner/postgres_mimiciii
    environment:
      - MIMIC_PASSWORD=mimic
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
      - BUILD_MIMIC=0
    container_name: ehr_adv_attack_postgres_mimiciii
    volumes:
      - ${LOCAL_SQL_DIR}:/mimiciii_queries
      - ${LOCAL_OUTPUT_CSV}:/mimiciii_query_results
      - ${LOCAL_DB}:/var/lib/postgresql/data
    ports:
      - 5555:5432
    init: true
    stdin_open: true
    tty: true

  postgres_mimiciii_permissions:
    image: duanegoodner/postgres_mimiciii
    user: root
    volumes:
      - ${LOCAL_DB}:/var/lib/postgresql/data
    entrypoint:
      [
        "/bin/bash",
        "/docker-entrypoint-initdb.d/postgres_data_permissions/main.sh"
      ]
    depends_on:
      - postgres_mimiciii
