version: '3.8'

services:

  ehr_aa:
    env_file:
      - .env
    image: ${IMAGE_NAME}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    #   args:
    #   - CONTAINER_DEVSPACE=${CONTAINER_DEVSPACE}
    container_name: ${CONTAINER_NAME}
    entrypoint:
       [
        "/bin/bash",
        "/usr/local/entrypoints/jbs/main.sh"
      ]
    volumes:
      - ${LOCAL_PROJECT_DIR}:${CONTAINER_PROJECT_DIR}
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:${CONTAINER_SSH_PORT}:22"
    init: true
    stdin_open: true
    tty: true

  postgres_mimiciii:
    image: duanegoodner/
    build:
      context: .
      dockerfile: Dockerfile.postgres.mimiciii

    environment:
      - BUILD_MIMIC=${DB_BUILD_MIMIC_ON_RUN}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - MIMIC_PASSWORD=${DB_MIMIC_PASSWORD}

    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - ${DB_LOCAL_CSV_DIR}:${DB_CONTAINER_CSV_DIR}
      - ${DB_LOCAL_DATA_DIR}:${DB_HOST_DATA_DIR}
    ports:
      - ${DB_HOST_PORT}:5432
    init: true
    stdin_open: true
    tty: true
